package:
  name: ta-lib
  version: !!str 0.4.8

source:
  fn: TA_Lib-0.4.8.tar.gz
  url: https://github.com/mrjbq7/ta-lib/archive/TA_Lib-0.4.8.tar.gz

requirements:
  build:
    - python
    - cython
    - numpy x.x
  run:
    - python
    - numpy x.x

test:
  imports:
    - talib

about:
  home: http://github.com/mrjbq7/ta-lib
  license: BSD License
