{% set data = load_setuptools() %}

package:
  name: zipline
  version: {{ environ.get('GIT_DESCRIBE_TAG', '')}}

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  {% if environ.get('GIT_DESCRIBE_NUMBER', '0') == '0' %}string: py{{ environ.get('PY_VER').replace('.', '') }}_0
  {% else %}string: py{{ environ.get('PY_VER').replace('.', '') }}_{{ environ.get('GIT_BUILD_STR', 'GIT_STUB') }}{% endif %}


source:
  git_url: ../../

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    {% for req in data.get('install_requires', []) -%}
    - {{req}}
    {% endfor %}

test:
  {#  When we include the tests module in the zipline package, we can use this:
  requires:
    {% for req in data.get('extras_require', {}).get('dev', []) -%}
    - {{req}}
    {% endfor %}
  #}
  # Python imports
  imports:
    - zipline

about:
  home: https://zipline.io
  license: Apache Software License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
